name: Build and push Docker image

on:
  push:
  workflow_dispatch:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

    - name: Setup binfmt_misc
      run: docker run --rm --privileged aptman/qus -s -- -p aarch64 arm

    - name: Login to GHCR
      if: github.ref == 'refs/heads/main' && github.repository == 'ikuaki1009/yunzai-docker-images'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push images
      run: |
        git clone https://github.com/yoimiya-kokomi/Miao-Yunzai.git -b master
        cd Miao-Yunzai
        sed -i "s|github.com/yoimiya-kokomi|gitee.com/yoimiya-kokomi|g" ./docker/Dockerfile
        sed -i "s/mirrors.ustc.edu.cn/deb.debian.org/g" ./docker/Dockerfile
        sed -i "s/pypi.tuna.tsinghua.edu.cn/pypi.org/g" ./docker/Dockerfile
        docker buildx build -t \
           ghcr.io/ikuaki1009/yunzai-docker-images:latest \
           --push \
           --platform "linux/amd64,linux/arm64" \
           ./docker
