name: Build and push Docker image

on:
  push:
  workflow_dispatch:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        CPU_ARCH:
          - aarch64
          - arm
          - x86_64
    steps:

    - name: Setup binfmt_misc
      if: (matrix.CPU_ARCH == 'aarch64') || (matrix.CPU_ARCH == 'arm')
      run: docker run --rm --privileged aptman/qus -s -- -p aarch64 arm

    - name: Build images
      run: |
        git clone https://github.com/ikuaki1009/Miao-Yunzai.git -b patch-1
        cd Miao-Yunzai
        case '${{ matrix.CPU_ARCH }}' in
          arm)     PLATFORM_TAG="linux/arm/v7";;
          aarch64) PLATFORM_TAG="linux/arm64";;
          *)       PLATFORM_TAG="linux/amd64";;
        esac
        docker buildx build -t \
           ikuaki1009/yunzai-docker-images:latest \
          --platform "$PLATFORM_TAG" \
          ./docker
    - name: Login to GHCR
      if: github.ref == 'refs/heads/master' && github.event_name != 'push' && github.repository == 'ikuaki1009/yunzai-docker-images'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push
      if: github.ref == 'refs/heads/master' && github.event_name != 'push' && github.repository == 'ikuaki1009/yunzai-docker-images'
      run: |
        docker push ghcr.io/ikuaki1009/yunzai-docker-images:latest
 
